name: My first workflow

on:
  push:
    branches:
        - main
        - feature/*
  pull_request:
    branches:
        - main
        - feature/*

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Print a message
              run: |
                echo "Hello, world!"
                echo "Hii we are learning github actions"
                ls -la
   