name: Generate ASCII

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '*/1 * * * *'
    # push:
    #     branches: 
    #         - main
jobs:
    generate-ascii:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Cowsay Program
              run: |
                sudo apt-get update -y
                sudo apt-get install cowsay -y
            - name: run ascii-script.sh
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh
              shell: bash
            - name: upload dragon.txt
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file-job1
                path: dragon.txt
    generate-ascii-2:
        needs: generate-ascii
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: run ascii-script1.sh
              run: |
                chmod +x ascii-script1.sh
                ./ascii-script1.sh
              shell: bash
            - name: Download dragon.txt
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file-job1
            - name: Upload dragon.txt
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file-job2
                path: dragon.txt
    generate-ascii-3:
        needs: generate-ascii-2
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: run ascii-script2.sh
              run: |
                chmod +x ascii-script2.sh
                ./ascii-script2.sh
              shell: bash
            - name: Download dragon.txt
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file-job2
            - name: read dragon.txt from job2
              run: |
                cat dragon.txt
              shell: bash
            

