name: Matrix Configuration

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os:
                    - ubuntu-latest
                    - ubuntu-22.04
                   
                images:
                    - hello-world
                    - nginx
                exclude:
                    - os: ubuntu-latest
                      images: nginx
                    - os: ubuntu-22.04
                      images: hello-world
                include:
                    - os: ubuntu-latest
                      images: alpine
                    
        runs-on: ${{ matrix.os }}
        steps:
            - name: Run the docker image ${{ matrix.images }}
              run: |
                docker run ${{ matrix.images }}
              shell: bash
        
